services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypw
      - MYSQL_DATABASE=selise_order_management
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypw
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
